spring.application.name=spring-boot-rest
spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username =postgres
spring.datasource.password = password
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update 
# Above line will automatically create a table if table is not present if present then it will update it
spring.jpa.show-sql = true
# This line will show the query used behind the scene on console
